const Salatlar = {
  baqlajon: new URL("./baqlajon.jpg", import.meta.url).href,
  gnezdogluxarya: new URL("./gnezdogluxarya.jpg", import.meta.url).href,
  guruziya: new URL("./guruziya.jpg", import.meta.url).href,
  kapriz: new URL("./kapriz.jpg", import.meta.url).href,
  tayskiy: new URL("./tayskiy.jpg", import.meta.url).href,
  tovuqbnsezan: new URL("./tovuqbnsezan.jpg", import.meta.url).href,
  vitaminlar: new URL("./vitaminlar.jpg", import.meta.url).href,
  yangiyunsalat: new URL("./yangiyunsalat.jpg", import.meta.url).href,
  achhiq: new URL("./achhiq.jpg", import.meta.url).href,
  alivie: new URL("./alivie.jpg", import.meta.url).href,
  arugulabnsalat: new URL("./arugulabnsalat.jpg", import.meta.url).href,
  bahorguldastasi: new URL("./bahor guldastasi.jpg", import.meta.url).href,
  baqlajonliksalat: new URL("./baqlajonliksalat.jpg", import.meta.url).href,
  bek: new URL("./bek.jpg", import.meta.url).href,
  fransuzcha: new URL("./gribnoy.jpg", import.meta.url).href,
  gribnoy: new URL("./yangiyunsalat.jpg", import.meta.url).href,
  lesnoybor: new URL("./lesnoybor.jpg", import.meta.url).href,
  monastirskaya: new URL("./monastirskaya.jpg", import.meta.url).href,
  mujskayaradost: new URL("./mujskayaradost.jpg", import.meta.url).href,
  nejnost: new URL("./nejnost.jpg", import.meta.url).href,
  qovoqcha: new URL("./qovoqcha.jpg", import.meta.url).href,
  qoyningtili: new URL("./qoyningtili.jpg", import.meta.url).href,
  qoziqornolivie: new URL("./qoziqornolivie.jpg", import.meta.url).href,
  risalka: new URL("./risalka.jpg", import.meta.url).href,
  sayor: new URL("./sayor.jpg", import.meta.url).href,
  smak: new URL("./smak.jpg", import.meta.url).href,
  tatibkorvazn: new URL("./tatibkorvazn.jpg", import.meta.url).href,
  tbilisi: new URL("./tbilisi.jpg", import.meta.url).href,
  victoriya: new URL("./victoriya.jpg", import.meta.url).href,
  vitamin: new URL("./vitamin.jpg", import.meta.url).href,
  yunoncha: new URL("./yunoncha.jpg", import.meta.url).href,
  yunonchagazak: new URL("./yunonchagazak.jpg", import.meta.url).href,
};
export default Salatlar;
