import Shashlik from "./shashlik";
import Salatlar from "./salatlar";
import SamarqandOsh from "./samarqand-osh";
import MilliyTaomlar from "./milliy-taomlar";
import YevropaTaomlari from "./yevropa-taomlari";
import Ichimliklar from "./ichimliklar";
import BirinchiTaomlar from "./birinchi-taomlar";
const {
  chuchvara,
  turkshorva,
  mastava,
  shorva,
  suplapsha,
  yashilkaram,
  salyonka,
} = BirinchiTaomlar;
const {
  shashlik10,
  shashlik5,
  beshpanja,
  pamidorshashlik,
  shashlikmoloty,
  shashlikmolotycharvi,
  shashlikmolotykichkina,
  shashliknapaleon,
  shashlikrulet,
} = Shashlik;
const {
  baqlajon,
  gnezdogluxarya,
  guruziya,
  kapriz,
  tayskiy,
  tovuqbnsezan,
  vitaminlar,
  yangiyunsalat,
  achhiq,
  alivie,
  arugulabnsalat,
  bahorguldastasi,
  bek,
  fransuzcha,
  gribnoy,
  lesnoybor,
  monastirskaya,
  mujskayaradost,
  nejnost,
  qovoqcha,
  qoyningtili,
  qoziqornolivie,
  risalka,
  sayor,
  smak,
  tatibkorvazn,
  tbilisi,
  victoriya,
  vitamin,
  yunoncha,
} = Salatlar;
const {
  achichuk,
  anzur,
  bahorsalat,
  marinat,
  salyonny,
  samarqandosh7,
  samarqandoshbutun,
  turp,
} = SamarqandOsh;
const {
  chaxoxbili,
  dolma,
  jizsamarqand,
  jizumakay,
  qozichoqq,
  qozichoqy,
  qozonkabob,
  vaguri,
  manti,
} = MilliyTaomlar;
const {
  balonezapastasi,
  gabyadina,
  goshtsay,
  kolbaski,
  ziqorinligosht,
  sabzavotbnmedalyon,
  sachkabob,
  sachtova,
  alfredonmakaron,
  assortibek,
  baraninapoder,
  baraninapodom,
  barbekyutovuq,
  goshtset,
  kareyagnyon,
  makaronfarfalle,
  qozichoqbogimi,
  steakderev,
  steakfuji,
  steakribay,
  steaktibon,
  tovuqkokrak,
} = YevropaTaomlari;
const {
  ananaslisok1,
  chortoq,
  cola,
  pepsi,
  fanta,
  olchalisok1,
  olmalisok1,
  pamidorlisok1,
  sprite,
  suv,
} = Ichimliklar;
export const foods = [
  {
    food_id: 1,
    title: "Birinchi taomlar",
    link: "birinchi-taomlar",
    url: chuchvara,
    props: [
      {
        id: 1,
        title: "Chuchvara",
        quantity: 0,
        price: 24150 ,
        url: chuchvara,
      },
      {
        id: 2,
        title: "Tovuq Sho'rva",
        quantity: 0,
        price: 16100 ,
        url: suplapsha,
      },
      {
        id: 3,
        title: "Mastava",
        quantity: 0,
        price: 27600 ,
        url: mastava,
      },
      {
        id: 4,
        title: "Sho'rva",
        quantity: 0,
        price: 29900 ,
        url: shorva,
      },
      {
        id: 5,
        title: "Sup-Lapsha s Frikadelkami",
        quantity: 0,
        price: 18400 ,
        url: suplapsha,
      },
      {
        id: 6,
        title: "Turkcha Sho'rva",
        quantity: 0,
        price: 24150 ,
        url: turkshorva,
      },
      {
        id: 7,
        title: "Yashil Karom Sho'rva",
        quantity: 0,
        price: 28750 ,
        url: yashilkaram,
      },
      {
        id: 8,
        title: "Shi zelyonniy s frikadelkami",
        quantity: 0,
        price: 29900 ,
        url: "https://vkusno-i-prosto.ru/wp-content/uploads/2012/07/shhi-s-frikadelkami.jpg",
      },
      {
        id: 9,
        title: "Sup chechivitsi",
        quantity: 0,
        price: 26450 ,
        url: "https://i.ytimg.com/vi/uiR9Q5m8NMs/mqdefault.jpg",
      },
      {
        id: 10,
        title: "Xash",
        quantity: 0,
        price: 44850 ,
        url: "https://i.ytimg.com/vi/6KYCcH-8L18/maxresdefault.jpg",
      },
      {
        id: 11,
        title: "Solyanka",
        quantity: 0,
        price: 35650 ,
        url: salyonka,
      },
      {
        id: 12,
        title: "Bo'rsh",
        quantity: 0,
        price: 28750 ,
        url: "https://zira.uz/wp-content/uploads/2018/11/borw-3-1.jpg",
      },
    ],
  },
  {
    food_id: 2,
    title: "Shashlik",
    link: "shashlik",
    url: shashlik10,
    props: [
      {
        id: 1,
        title: "Shashlik Assorti Katta 10 kishilik",
        quantity: 0,
        price: 633650 ,
        url: shashlik10,
      },
      {
        id: 2,
        title: "Shashlik Assorti Kichkina 5 kishilik",
        quantity: 0,
        price: 331200 ,
        url: shashlik5,
      },
      {
        id: 3,
        title: "Besh panja qo'zichoq",
        quantity: 0,
        price: 95450 ,
        url: beshpanja,
      },
      {
        id: 4,
        title: "'Besh Panja' mol go'shti",
        quantity: 0,
        price: 116150 ,
        url: beshpanja,
      },
      {
        id: 5,
        title: "Pomidor Shashlik",
        quantity: 0,
        price: 4600 ,
        url: pamidorshashlik,
      },
      {
        id: 6,
        title: "Shashlik Moloty",
        quantity: 0,
        price: 40250 ,
        url: shashlikmoloty,
      },
      {
        id: 7,
        title: "Shashlik Moloty charvi",
        quantity: 0,
        price: 56350 ,
        url: shashlikmolotycharvi,
      },
      {
        id: 8,
        title: "Shashlik Moloty kichkina",
        quantity: 0,
        price: 25300 ,
        url: shashlikmolotykichkina,
      },
      {
        id: 9,
        title: "Shashlik Napoleon",
        quantity: 0,
        price: 52900 ,
        url: shashliknapaleon,
      },
      {
        id: 10,
        title: "Shashlik Rulet",
        quantity: 0,
        price: 54050 ,
        url: shashlikrulet,
      },
      {
        id: 11,
        title: "Qo'zichq bolagi",
        quantity: 0,
        price: 47150 ,
        url: "https://daryo.uz/cache/2020/05/Pinterest-1254x1161.jpg",
      },
      {
        id: 13,
        title: "Qo'zichoq qovurg'alari",
        quantity: 0,
        price: 70150 ,
        url: "https://extra-sugar.ru/uploads/pypthumb-nux-722x587.jpg",
      },
      {
        id: 14,
        title: "Qo'zi beli",
        quantity: 0,
        price: 87400 ,
        url: "https://daryo.uz/cache/2020/05/Pinterest-1254x1161.jpg",
      },
      {
        id: 15,
        title: "Kavkaz Qo'zisi",
        quantity: 0,
        price: 94300 ,
        url: "https://zira.uz/wp-content/uploads/2020/02/baranina-zapechennaya-v-gorchice.jpg",
      },
      {
        id: 16,
        title: "Tovuq Oyoqlari",
        quantity: 0,
        price: 39100 ,
        url: "https://daryo.uz/cache/2022/02/photo_2022-02-21_23-28-01-1280x640.jpg",
      },
      {
        id: 17,
        title: "Tovuq Qanotlari",
        quantity: 0,
        price: 34500 ,
        url: "https://zira.uz/wp-content/uploads/2020/05/krylyshki_v_medovo_soevom_marinade_s_kukuruzoy_2.jpg",
      },
      {
        id: 18,
        title: "Tovuq Golen",
        quantity: 0,
        price: 52900 ,
        url: "https://yukber.uz/image/cache/catalog/product/YK0350/YK0350-700x700.jpg",
      },
      {
        id: 19,
        title: "Mol go'shti bo'lagi",
        quantity: 0,
        price: 56350 ,
        url: "https://zira.uz/wp-content/uploads/2021/02/gestollo_govyadina_tushenaya_v_souse_sacebeli_2.jpg",
      },
      {
        id: 20,
        title: "Mol go'sht bo'lagi kichkina",
        quantity: 0,
        price: 28750 ,
        url: "https://zira.uz/wp-content/uploads/2021/02/gestollo_govyadina_tushenaya_v_souse_sacebeli_2.jpg",
      },
    ],
  },
  {
    food_id: 3,
    title: "Salatlar",
    link: "salatlar",
    url: bahorsalat,
    props: [
      {
        id: 1,
        title: "Baqlajonlik",
        quantity: 0,
        price: 23000 ,
        url: baqlajon,
      },
      {
        id: 2,
        title: "Gnezdo Gluxarya",
        quantity: 0,
        price: 36800 ,
        url: gnezdogluxarya,
      },
      {
        id: 3,
        title: "Gruziya",
        quantity: 0,
        price: 33350 ,
        url: guruziya,
      },
      {
        id: 4,
        title: "Kapriz",
        quantity: 0,
        price: 75900 ,
        url: kapriz,
      },
      {
        id: 5,
        title: "Tayskiy",
        quantity: 0,
        price: 40250 ,
        url: tayskiy,
      },
      {
        id: 6,
        title: "Tovuq bilan Sezar",
        quantity: 0,
        price: 51750 ,
        url: tovuqbnsezan,
      },
      {
        id: 7,
        title: "Vitaminlar To'plami",
        quantity: 0,
        price: 36800 ,
        url: vitaminlar,
      },
      {
        id: 8,
        title: "Yangi Yunoncha Salat",
        quantity: 0,
        price: 58650 ,
        url: yangiyunsalat,
      },
      {
        id: 9,
        title: "Yunoncha",
        quantity: 0,
        price: 34500 ,
        url: yunoncha,
      },
      {
        id: 10,
        title: "Tatib ko'r va Vazn yo'qot",
        quantity: 0,
        price: 35650 ,
        url: tatibkorvazn,
      },
      {
        id: 11,
        title: "Arugula bilan salat",
        quantity: 0,
        price: 36800 ,
        url: arugulabnsalat,
      },
      {
        id: 12,
        title: "Vitaminlar",
        quantity: 0,
        price: 36800 ,
        url: vitamin,
      },
      {
        id: 13,
        title: "Smak",
        quantity: 0,
        price: 24150 ,
        url: smak,
      },
      {
        id: 14,
        title: "idil",
        quantity: 0,
        price: 28750 ,
        url: "https://altynachar.com/mtk44/43-thickbox_default/sezar-salat.jpg",
      },
      {
        id: 15,
        title: "Bahor guldastasi",
        quantity: 0,
        price: 27600 ,
        url: bahorguldastasi,
      },
      {
        id: 16,
        title: "Qovoqcha",
        quantity: 0,
        price: 19550 ,
        url: qovoqcha,
      },
      {
        id: 17,
        title: "Qo'ziqorin Olivie",
        quantity: 0,
        price: 31050 ,
        url: qoziqornolivie,
      },
      {
        id: 18,
        title: "Lesnoy Bor",
        quantity: 0,
        price: 26450 ,
        url: lesnoybor,
      },
      {
        id: 19,
        title: "Nejnost",
        quantity: 0,
        price: 35650 ,
        url: nejnost,
      },
      {
        id: 20,
        title: "Gribnoy chudo",
        quantity: 0,
        price: 34500 ,
        url: gribnoy,
      },
      {
        id: 21,
        title: "Rusalka",
        quantity: 0,
        price: 50600 ,
        url: risalka,
      },
      {
        id: 22,
        title: "Sayor",
        quantity: 0,
        price: 29900 ,
        url: sayor,
      },
      {
        id: 23,
        title: "Olivie",
        quantity: 0,
        price: 26450 ,
        url: alivie,
      },
      {
        id: 24,
        title: "Monastirskaya Izba",
        quantity: 0,
        price: 58650 ,
        url: monastirskaya,
      },
      {
        id: 25,
        title: "Qo'yning Tili",
        quantity: 0,
        price: 35650 ,
        url: qoyningtili,
      },
      {
        id: 26,
        title: "Fransuzcha",
        quantity: 0,
        price: 26450 ,
        url: fransuzcha,
      },
      {
        id: 27,
        title: "Mujskaya radost",
        quantity: 0,
        price: 66700 ,
        url: mujskayaradost,
      },
      {
        id: 28,
        title: "Achсhiq",
        quantity: 0,
        price: 43700 ,
        url: achhiq,
      },
      {
        id: 29,
        title: "Vdohnoveniy",
        quantity: 0,
        price: 51750 ,
        url: qoyningtili,
      },
      {
        id: 30,
        title: "Viktoriya",
        quantity: 0,
        price: 44850 ,
        url: victoriya,
      },
      {
        id: 31,
        title: "Bek",
        quantity: 0,
        price: 54050 ,
        url: bek,
      },
      {
        id: 32,
        title: "Tbilisi",
        quantity: 0,
        price: 37950 ,
        url: tbilisi,
      },
      {
        id: 33,
        title: "Selyodka shuba",
        quantity: 0,
        price: 29900 ,
        url: "https://i0.wp.com/cdn.lifehacker.ru/wp-content/uploads/2018/12/shutterstock_510916834_1576580260-e1576580280189-1600x800.jpg",
      },
      {
        id: 34,
        title: "Selyodka krestyansky",
        quantity: 0,
        price: 40250 ,
        url: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Selyodka_pod_Shuboy_at_White_Nights%2C_Beijing_%2820201023130349%29.jpg",
      },
      {
        id: 35,
        title: "Mimoza",
        quantity: 0,
        price: 29900 ,
        url: "https://zira.uz/wp-content/uploads/2019/11/mimoza.jpg",
      },
      {
        id: 36,
        title: "Chakka",
        quantity: 0,
        price: 11500 ,
        url: "https://www.restoran-shafran.uz/image/cache/catalog/product/salati/chakka-750x500.jpg",
      },
      {
        id: 37,
        title: "Limon",
        quantity: 0,
        price: 11500 ,
        url: "https://zira.uz/wp-content/uploads/2021/04/salat-s-ogurcami-i-brynzoy-3.jpg",
      },
      {
        id: 39,
        title: "Teshinskiy Tili",
        quantity: 0,
        price: 18400 ,
        url: "https://cdn.cakelab.uz/products/thumbs/1_1643830607.jpg",
      },
      {
        id: 40,
        title: "Biryuzoviy zelyonim",
        quantity: 0,
        price: 29900 ,
        url: "https://play-lh.googleusercontent.com/QhFGUoGcF53W_ls55LTjpU2xSRoyPI2_v0GSyBzac7RrBsUqzdM_Fkvn9sYAaic8HA",
      },
    ],
  },
  {
    food_id: 4,
    title: "Samarqand Osh",
    link: "samarqand-osh",
    url: samarqandosh7,
    props: [
      {
        id: 1,
        title: "Samarqand Osh Butun",
        quantity: 0,
        price: 42550 ,
        url: samarqandoshbutun,
      },
      {
        id: 2,
        title: "Samarqand Osh 0.7",
        quantity: 0,
        price: 39100 ,
        url: samarqandosh7,
      },
      {
        id: 3,
        title: "Bahor Salat",
        quantity: 0,
        price: 11500 ,
        url: bahorsalat,
      },
      {
        id: 4,
        title: "Marinat",
        quantity: 0,
        price: 11500 ,
        url: marinat,
      },
      {
        id: 5,
        title: "Salyonny",
        quantity: 0,
        price: 11500 ,
        url: salyonny,
      },
      {
        id: 6,
        title: "Turp Chakka",
        quantity: 0,
        price: 11500 ,
        url: turp,
      },
      {
        id: 7,
        title: "Achichuk",
        quantity: 0,
        price: 12650 ,
        url: achichuk,
      },
      {
        id: 8,
        title: "Anzur",
        quantity: 0,
        price: 14950 ,
        url: anzur,
      },
      {
        id: 9,
        title: "Pay",
        quantity: 0,
        price: 31050 ,
        url: "https://www.tenderfilet.com/dw/image/v2/BBVM_PRD/on/demandware.static/-/Sites-colony-master-catalog/default/dwecf528ae/large/sub_33/006627_Replace_FA19.png?sw=680&sh=680&sm=fit",
      },
      {
        id: 10,
        title: "Qo'shimcha go'sht",
        quantity: 0,
        price: 31050 ,
        url: "https://darakchi.uz/storage/37/8a/20/35779/conversions/-_-85tluytfK-_w366Jn1vROmmN2wN4O-xl.jpg",
      },
      {
        id: 11,
        title: "Qazi 1 bo'lak",
        quantity: 0,
        price: 9200 ,
        url: "https://media-cdn.tripadvisor.com/media/photo-s/17/c0/02/f0/qazi.jpg",
      },
      {
        id: 12,
        title: "Bedana Tuxum 1 dona",
        quantity: 0,
        price: 1150 ,
        url: "https://i3.wp.com/avitsenna.uz/wp-content/uploads/2021/03/ovos-de-codorna-1280x720-e1587578125462.jpg",
      },
      {
        id: 13,
        title: "Gurob",
        quantity: 0,
        price: 6900 ,
        url: "https://roaminjulietguatemala.files.wordpress.com/2018/07/img_6930.jpg?w=768",
      },
      {
        id: 14,
        title: "Pomidor sharbati",
        quantity: 0,
        price: 11500 ,
        url: "https://hordiq.uz/wp-content/uploads/2021/07/photo_2021-07-09_12-38-13-696x464.jpg?lang=lat",
      },
      {
        id: 15,
        title: "Non",
        quantity: 0,
        price: 8050 ,
        url: "https://uzdon.uz/img/news/906/DSC08985.jpg",
      },
      {
        id: 16,
        title: "Slayonniy patir",
        quantity: 0,
        price: 8050 ,
        url: "https://arbuz.com/wp-content/uploads/2019/04/Flaky-Layered-Flatbread-47.jpg",
      },
    ],
  },
  {
    food_id: 5,
    title: "Milliy taomlar",
    link: "milliy-taomlar",
    url: chaxoxbili,
    props: [
      {
        id: 1,
        title: "Chaxoxbili",
        quantity: 0,
        price: 81650 ,
        url: chaxoxbili,
      },
      {
        id: 2,
        title: "Dolma",
        quantity: 0,
        price: 54050 ,
        url: dolma,
      },
      {
        id: 3,
        title: "Jiz Samarqand",
        quantity: 0,
        price: 184000 ,
        url: jizsamarqand,
      },
      {
        id: 4,
        title: "Jiz Umakay",
        quantity: 0,
        price: 78200 ,
        url: jizumakay,
      },
      {
        id: 5,
        title: "Qo'zichoq Qovurg'asi",
        quantity: 0,
        price: 142600 ,
        url: qozichoqq,
      },
      {
        id: 6,
        title: "Qo'zichoq Yelkasi",
        quantity: 0,
        price: 473800 ,
        url: qozichoqy,
      },
      {
        id: 7,
        title: "Qozon Kabob",
        quantity: 0,
        price: 96600 ,
        url: qozonkabob,
      },
      {
        id: 8,
        title: "Vaguri",
        quantity: 0,
        price: 133400 ,
        url: vaguri,
      },
      {
        id: 9,
        title: "Manti",
        quantity: 0,
        price: 42550 ,
        url: manti,
      },
      {
        id: 10,
        title: "Lag`mon",
        quantity: 0,
        price: 33350 ,
        url: "https://avatars.mds.yandex.net/get-altay/6950449/2a0000018499c1e8b9cff1bd6f070248fa41/L_height",
      },
    ],
  },
  {
    food_id: 6,
    title: "Yevropa taomlari",
    link: "yevropa-taomlari",
    url: balonezapastasi,
    props: [
      {
        id: 1,
        title: "Baloneza Pastasi",
        quantity: 0,
        price: 58650 ,
        url: balonezapastasi,
      },
      {
        id: 2,
        title: "Govyadina po-domashnemu",
        quantity: 0,
        price: 56350 ,
        url: gabyadina,
      },
      {
        id: 3,
        title: "Go'sht Say",
        quantity: 0,
        price: 75900 ,
        url: goshtsay,
      },
      {
        id: 4,
        title: "Kolbaski",
        quantity: 0,
        price: 92000 ,
        url: kolbaski,
      },
      {
        id: 5,
        title: "Qo'ziqorinli Go'sht",
        quantity: 0,
        price: 89700 ,
        url: ziqorinligosht,
      },
      {
        id: 6,
        title: "Sabzavotlar bilan medalyon",
        quantity: 0,
        price: 103500 ,
        url: sabzavotbnmedalyon,
      },
      {
        id: 7,
        title: "Sach Kabob",
        quantity: 0,
        price: 108100 ,
        url: sachkabob,
      },
      {
        id: 8,
        title: "Sach Tava",
        quantity: 0,
        price: 64400 ,
        url: sachtova,
      },
      {
        id: 9,
        title: "Steak Fuji",
        quantity: 0,
        price: 13250 ,
        url: steakfuji,
      },
      {
        id: 10,
        title: "Steak Ribay",
        quantity: 0,
        price: 10250 ,
        url: steakribay,
      },
      {
        id: 12,
        title: "Poperechnik",
        quantity: 0,
        price: 43700 ,
        url: "https://qrmenu.marvarid.kz/uploads/posts/2022-09/1663759472_assorti-iz-svezhih-ovoschej-po-gruzinski.jpg",
      },
      {
        id: 13,
        title: "Go'sht Set",
        quantity: 0,
        price: 34615.00 ,
        url: goshtset,
      },
      {
        id: 14,
        title: "Assorti Trio",
        quantity: 0,
        price: 417450 ,
        url: "https://qrmenu.marvarid.kz/uploads/posts/2022-09/1663759667_assorti-iz-zeleni-po-gruzinsi.jpg",
      },
      {
        id: 15,
        title: "Baranina po domashniy",
        quantity: 0,
        price: 52900 ,
        url: baraninapodom,
      },
      {
        id: 16,
        title: "Baranin po-derevenski",
        quantity: 0,
        price: 94300 ,
        url: baraninapoder,
      },
      {
        id: 17,
        title: "Tovuq Ko'krak",
        quantity: 0,
        price: 56350 ,
        url: tovuqkokrak,
      },
      {
        id: 18,
        title: "Makaron farfalle",
        quantity: 0,
        price: 47150 ,
        url: makaronfarfalle,
      },
      {
        id: 19,
        title: "Myaso po kitayskiy",
        quantity: 0,
        price: 80500 ,
        url: "https://zira.uz/wp-content/uploads/2020/12/myaso-po-kitai--ski-4.jpg",
      },
      {
        id: 20,
        title: "Steak Tibon",
        quantity: 0,
        price: 109250 ,
        url: steaktibon,
      },
      {
        id: 21,
        title: "Steak Derevyanskiy",
        quantity: 0,
        price: 126500 ,
        url: steakderev,
      },
      {
        id: 22,
        title: "Assorti Bek",
        quantity: 0,
        price: 800400 ,
        url: assortibek,
      },
      {
        id: 23,
        title: "Assorti Samarqand",
        quantity: 0,
        price: 639400 ,
        url: "https://media-cdn.tripadvisor.com/media/photo-s/22/ab/72/a9/salted-salmon.jpg",
      },
      {
        id: 24,
        title: "Qo'zichoq bo'g'imi",
        quantity: 0,
        price: 97750 ,
        url: qozichoqbogimi,
      },
      {
        id: 25,
        title: "Kare Yagnyonka s ovoshami",
        quantity: 0,
        price: 83950 ,
        url: kareyagnyon,
      },
      {
        id: 26,
        title: "Barbekyu Tovuq",
        quantity: 0,
        price: 37800 ,
        url: barbekyutovuq,
      },
      {
        id: 27,
        title: "Alfredon Makaron",
        quantity: 0,
        price: 55200 ,
        url: alfredonmakaron,
      },
      {
        id: 28,
        title: "Tovuq va sabzavotlar",
        quantity: 0,
        price: 46000 ,
        url: "https://daryo.uz/cache/2021/01/photo_2021-01-07_17-27-19-680x453-680x453.jpg",
      },
      {
        id: 29,
        title: "Язык в сливках",
        quantity: 0,
        price: 74750 ,
        url: "https://s1.eda.ru/StaticContent/Photos/170228185005/200502165159/p_O.jpg",
      },
      {
        id: 30,
        title: "Крылишки в томатном соусе",
        quantity: 0,
        price: 4945.00 ,
        url: "https://www.nyamburg.ru/wp-content/uploads/kurinyye-krylyshki-na-skovorode-v-tomatnom-souse.jpg",
      },
    ],
  },
  {
    food_id: 7,
    title: "Ichimliklar",
    link: "ichimliklar",
    url: suv,
    props: [
      {
        id: 1,
        title: "Вода 1,5",
        quantity: 0,
        price: 5350 ,
        url: suv,
      },
      {
        id: 2,
        title: "Спрайт 1.5",
        quantity: 0,
        price: 20700 ,
        url: sprite,
      },
      {
        id: 3,
        title: "Фанта 1.5",
        quantity: 0,
        price: 20700 ,
        url: fanta,
      },
      {
        id: 4,
        title: "Coca-Cola 1.5L",
        quantity: 0,
        price: 20700 ,
        url: cola,
      },
      {
        id: 5,
        title: "Сок Яблоко 'Соч.долина' 1л",
        quantity: 0,
        price: 20700 ,
        url: olmalisok1,
      },
      {
        id: 6,
        title: "Сок Вишня 'Соч.долина' 1л",
        quantity: 0,
        price: 20700 ,
        url: olchalisok1,
      },
      {
        id: 7,
        title: "Сок Мулти 'Соч.долина' 1л",
        quantity: 0,
        price: 20700 ,
        url: ananaslisok1,
      },
      {
        id: 8,
        title: "Сок Томат 'Соч.долина' 1л",
        quantity: 0,
        price: 20700 ,
        url: pamidorlisok1,
      },
      {
        id: 9,
        title: "Чорток 0.5",
        quantity: 0,
        price: 11500 ,
        url: chortoq,
      },
      {
        id: 10,
        title: "Pepsi 1.5L",
        quantity: 0,
        price: 20700 ,
        url: pepsi,
      },
    ],
  },
];
